local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf',
    function()
        builtin.find_files({ no_ignore = true })
    end, { desc = "Find File no Ignore" })
vim.keymap.set('n', '<leader>pp', builtin.git_files, { desc = "Find Git Files" })
vim.keymap.set('n', '<leader>pg', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = "Grep Search" })
vim.keymap.set('x', '<leader>pg', builtin.grep_string, { desc = "Grep String Search" })
vim.keymap.set('n', '<leader>ph', builtin.help_tags, { desc = "Help Tags" })
