local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', 
function()
	builtin.find_files({ no_ignore = true })
end)
vim.keymap.set('n', '<leader>pp', builtin.git_files, {})
vim.keymap.set('n', '<leader>pg', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('x', '<leader>pg',builtin.grep_string,{})
vim.keymap.set('n', '<leader>ph', builtin.help_tags, {})
